# 使用h2快速测试--使用liquibase管理h2的数据
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:h2:mem:test  #内存模式
#    url: jdbc:log4jdbc:h2:file:D:\git\demo\demo-aop-log\target\temp\h2  # 文件模式
    username: root
    password: 123456
  # liquibase 支持h2对应的changelog.xml要写对
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-master.xml

  h2:
    console:
      # 默认关闭 http://host:port/h2-console (url=jdbc:h2:mem:test / 账号密码=root/test 和上面的datasource配置保持一致)
      enabled: true
      settings:
        # 不开启报错: Sorry, remote connections ('webAllowOthers') are disabled on this server.
        web-allow-others: true

