# 使用h2快速测试
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:log4jdbc:h2:mem:test
    username: root
    password: 123456
  # liquibase不支持h2数据库,springboot的LiquibaseAutoConfiguration会自动装配开启,因此要显式关闭
  liquibase:
    enabled: false

  h2:
    console:
      # 默认关闭 http://host:port/h2-console (url=jdbc:h2:mem:test / 账号密码=root/test 和上面的datasource配置保持一致)
      enabled: true
      settings:
        # 不开启报错: Sorry, remote connections ('webAllowOthers') are disabled on this server.
        web-allow-others: true

