spring.datasource.dynamic.enabled=true
spring.datasource.dynamic.transaction.enabled=false
spring.datasource.dynamic.header=db-type
spring.datasource.dynamic.primary=master
spring.datasource.dynamic.check=true
spring.datasource.dynamic.strict=true
spring.datasource.dynamic.datasource.master.driver-class-name=org.h2.Driver
spring.datasource.dynamic.datasource.master.url=jdbc:h2:mem:test
spring.datasource.dynamic.datasource.master.username=root
spring.datasource.dynamic.datasource.master.password=123456
spring.datasource.dynamic.datasource.db1.driver-class-name=org.h2.Driver
spring.datasource.dynamic.datasource.db1.url=jdbc:h2:file:.\\target\\temp\\h2\\db02
spring.datasource.dynamic.datasource.db1.username=root
spring.datasource.dynamic.datasource.db1.password=123456
spring.datasource.dynamic.datasource.db2.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.dynamic.datasource.db2.url=jdbc:mysql://192.168.4.188:3306/db_demo_01?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
spring.datasource.dynamic.datasource.db2.username=root
spring.datasource.dynamic.datasource.db2.password=123456
