pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('docker-build') {
            agent any
            steps {
                sh '''cd /var/jenkins_home/workspace/create_docker_images/target
                cp ../jenkins/docker/Dockerfile ./
                docker build -t testproject .'''
            }
        }
    }
}